/// What a discovered radio appears to be, used only to pick an icon.
///
/// There is no `wifi` member. There used to be, because the old scan fabricated
/// a Wi-Fi "device" from the phone's own network — but nothing on a Wi-Fi network
/// is a pairable device from this app's point of view, so the case never had a
/// real value to hold.
enum BleDeviceType {
  keyholder,
  headphones,
  watch,
  generic,
  bluetooth,
}

/// Where a keyholder stands with respect to ownership.
///
/// This is the state the security model turns on, so it is modelled explicitly
/// rather than inferred from a pile of booleans. Only [BleDeviceType.keyholder]
/// devices ever leave [unknown].
enum OwnershipState {
  /// Not a keyholder, or we have not talked to it yet.
  unknown,

  /// The keyholder has no owner. It can be claimed — but only while its
  /// physical button is held.
  unclaimed,

  /// Claimed, and the stored owner key on this phone matches.
  claimedByMe,

  /// Claimed by somebody else. The firmware will refuse us, so the UI must not
  /// offer a Connect button.
  claimedByOther,

  /// Challenge sent, waiting on the response.
  authenticating,

  /// Challenge passed; commands are accepted.
  authenticated,

  /// Challenge failed or timed out.
  authFailed,

  /// Too many failed attempts — the keyholder is refusing connections.
  lockedOut,
}

class BleDevice {
  final String id;
  final String name;
  final int rssi;
  final String macAddress;
  final BleDeviceType deviceType;
  final bool isConnected;
  final bool isPrimary;

  /// Ownership status, for keyholders.
  final OwnershipState ownership;

  /// True for entries generated by Demo Mode.
  ///
  /// Carried on the model rather than tracked separately so that anything which
  /// acts on a device — connecting, claiming, authenticating — can refuse a
  /// simulated one outright. A demo entry must never be mistaken for hardware.
  final bool isDemo;

  BleDevice({
    required this.id,
    required this.name,
    required this.rssi,
    required this.macAddress,
    this.deviceType = BleDeviceType.generic,
    this.isConnected = false,
    this.isPrimary = false,
    this.ownership = OwnershipState.unknown,
    this.isDemo = false,
  });

  bool get isKeyholder => deviceType == BleDeviceType.keyholder;

  /// True when this keyholder is locked to a different owner, so pairing with it
  /// is impossible until that owner releases it.
  bool get isLockedToAnotherOwner => ownership == OwnershipState.claimedByOther;

  BleDevice copyWith({
    String? id,
    String? name,
    int? rssi,
    String? macAddress,
    BleDeviceType? deviceType,
    bool? isConnected,
    bool? isPrimary,
    OwnershipState? ownership,
    bool? isDemo,
  }) {
    return BleDevice(
      id: id ?? this.id,
      name: name ?? this.name,
      rssi: rssi ?? this.rssi,
      macAddress: macAddress ?? this.macAddress,
      deviceType: deviceType ?? this.deviceType,
      isConnected: isConnected ?? this.isConnected,
      isPrimary: isPrimary ?? this.isPrimary,
      ownership: ownership ?? this.ownership,
      isDemo: isDemo ?? this.isDemo,
    );
  }
}
